# Generated by Django 4.2.3 on 2023-08-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_user_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
